### ISSUE TITLE
Unable to find node-mavlink-0.1.0.tgz to download

### ISSUE THREAD

**Issue by strotech** [ifrunistuttgart/node-mavlink#2]
Please provide a link to download the tgz file - node-mavlink-0.1.0.tgz

**Comment by pascalgross** [comment]
You are right - I'll fix that asap (hopefully today)

**Comment by strotech** [comment]
I am still unable to get the tgz file

**Comment by strotech** [comment]
Please confirm if there is any other way to install

**Comment by pascalgross** [comment]
Sorry for the delay. I'll take care of it today.
I'll let you know asap

**Comment by pascalgross** [comment]
Okay, still not fully tested (the npm package) but online: 
Run `npm i @ifrunistuttgart/node-mavlink`
You can find the package here: https://www.npmjs.com/package/@ifrunistuttgart/node-mavlink

**Comment by pascalgross** [comment]
I'll close this issue for now. Feel free to reopen, if the problem persists.
